# This is the docker-compose.yml for your Hugging Face Space
services:
  backend:
    # Pull the pre-built image from Docker Hub
    image: eboneoarcadia/sophiaweaver-backend:latest
    ports:
      - "8000:8000"
    volumes:
      # This mounts the model files from the Space's repo into the container
      - ./trained_models:/app/backend/trained_models
    environment:
      PYTHONUNBUFFERED: 1
    restart: unless-stopped

  frontend:
    # Pull the pre-built image from Docker Hub
    image: eboneoarcadia/sophiaweaver-frontend:latest
    ports:
      # Hugging Face Spaces exposes port 7860 for web UIs
      - "7860:8501"
    environment:
      # The frontend can find the backend using its service name
      BACKEND_API_URL: http://backend:8000
      PYTHONUNBUFFERED: 1
    depends_on:
      - backend
    restart: unless-stopped