services:
  backend:
    build: ./app/backend
    image: eboneoarcadia/sophiaweaver-backend:latest
    container_name: sophiaweaver-backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend/trained_models:/app/backend/trained_models
    environment:
      PYTHONUNBUFFERED: 1
    restart: unless-stopped

  frontend:
    build: ./app/frontend
    image: eboneoarcadia/sophiaweaver-frontend:latest
    container_name: sophiaweaver-frontend-container
    ports:
      - "8501:8501"
    environment:
      BACKEND_API_URL: http://backend:8000
      PYTHONUNBUFFERED: 1
    depends_on:
      - backend
    restart: unless-stopped